name: Deploy
on:
  push:
    branches: [ main ]
    paths: 
      - compose.yaml
  workflow_dispatch: 

jobs:
  deploy-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Webhook
        id: deploy-api
        uses: tyrrrz/action-http-request@master
        with:
          url: ${{ secrets.DEPLOYMENT_WEBHOOK }}
          method: POST
          headers:
          body: '{}'
          retry-count: 3
          retry-delay: 500
      
      - name: Print outputs
        run: |
          echo "Status: ${{ steps.deploy-api.outputs.status }}"
          echo "Success: ${{ steps.deploy-api.outputs.success }}"
