name: Validate-YAML

on: 
  push:
    branches: [ main ]
    paths: compose.yaml
  pull_request:
    branches: [ main ]
    paths: compose.yaml
  

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint compose.yaml
